name: Latest Stable Versions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Fetch history and commit message
      run: |
        git fetch --prune --unshallow

    - name: Configure Git
      run: |
        git config user.name "moxbot"
        git config user.email "bot@mox.sh"

    - name: Setup credentials to access repositories
      run: git config --global url.https://${{ secrets.CR_TOKEN }}@github.com/.insteadOf https://github.com/

    - name: 01-test-schedule
      run: touch $(date +%F-%H%M%S)

    - name: Create Pull Request
      id: cpr
      uses: moxbot/create-pull-request@v3
      with:
        token: ${{ secrets.CR_TOKEN }}
        commit-message: "[Release] update Charts with the latest stable App versions"
        committer: moxbot <bot@mox.sh>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        title: "[Release] test01 latest stable Apps versions"
        body: |
          New versions of the Apps have been released, and the Charts have been updated.
          - PR auto-generated in the repo: [helm-charts][1]

           [1]: https://github.com/javimox/helm-charts
        branch: latest-stable-versions
        labels: update-appVersion
