name: Release Charts

on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'Release')"
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # step disabled
      # https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
      - name: Fetch history and commit message
        run: |
          git fetch --prune --unshallow
      #    echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})

      - name: Configure Git
        run: |
          git config user.name "moxbot"
          git config user.email "bot@mox.sh"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
    
